allowBuilds:
  bcrypto: true
  better-sqlite3: true
  bstring: true
  es5-ext: true
  lmdb: true
  msgpackr-extract: true
  nsfw: true
  protobufjs: true

minimumReleaseAgeExclude:
  - '@mainsail/api-common@0.0.1-evm.55'
  - '@mainsail/api-database@0.0.1-evm.55'
  - '@mainsail/api-development@0.0.1-evm.55'
  - '@mainsail/api-evm@0.0.1-evm.55'
  - '@mainsail/api-http@0.0.1-evm.55'
  - '@mainsail/api-sync@0.0.1-evm.55'
  - '@mainsail/api-transaction-pool@0.0.1-evm.55'
  - '@mainsail/blockchain-utils@0.0.1-evm.55'
  - '@mainsail/bootstrap@0.0.1-evm.55'
  - '@mainsail/cli@0.0.1-evm.55'
  - '@mainsail/configuration-generator@0.0.1-evm.55'
  - '@mainsail/consensus-storage@0.0.1-evm.55'
  - '@mainsail/consensus@0.0.1-evm.55'
  - '@mainsail/constants@0.0.1-evm.55'
  - '@mainsail/container@0.0.1-evm.55'
  - '@mainsail/contracts@0.0.1-evm.55'
  - '@mainsail/core@0.0.1-evm.55'
  - '@mainsail/crypto-address-base58@0.0.1-evm.55'
  - '@mainsail/crypto-address-keccak256@0.0.1-evm.55'
  - '@mainsail/crypto-block@0.0.1-evm.55'
  - '@mainsail/crypto-commit@0.0.1-evm.55'
  - '@mainsail/crypto-config@0.0.1-evm.55'
  - '@mainsail/crypto-hash-bcrypto@0.0.1-evm.55'
  - '@mainsail/crypto-key-pair-bls12-381@0.0.1-evm.55'
  - '@mainsail/crypto-key-pair-ecdsa@0.0.1-evm.55'
  - '@mainsail/crypto-messages@0.0.1-evm.55'
  - '@mainsail/crypto-proposal@0.0.1-evm.55'
  - '@mainsail/crypto-signature-bls12-381@0.0.1-evm.55'
  - '@mainsail/crypto-signature-ecdsa@0.0.1-evm.55'
  - '@mainsail/crypto-transaction@0.0.1-evm.55'
  - '@mainsail/crypto-validation@0.0.1-evm.55'
  - '@mainsail/crypto-wif@0.0.1-evm.55'
  - '@mainsail/crypto-worker@0.0.1-evm.55'
  - '@mainsail/database@0.0.1-evm.55'
  - '@mainsail/evm-api-worker@0.0.1-evm.55'
  - '@mainsail/evm-consensus@0.0.1-evm.55'
  - '@mainsail/evm-contracts@0.0.1-evm.55'
  - '@mainsail/evm-linux-arm64-gnu@0.0.1-evm.55'
  - '@mainsail/evm-linux-x64-gnu@0.0.1-evm.55'
  - '@mainsail/evm-service@0.0.1-evm.55'
  - '@mainsail/evm-state@0.0.1-evm.55'
  - '@mainsail/evm@0.0.1-evm.55'
  - '@mainsail/exceptions@0.0.1-evm.55'
  - '@mainsail/forger@0.0.1-evm.55'
  - '@mainsail/kernel@0.0.1-evm.55'
  - '@mainsail/logger-pino@0.0.1-evm.55'
  - '@mainsail/networking-ntp@0.0.1-evm.55'
  - '@mainsail/p2p@0.0.1-evm.55'
  - '@mainsail/processor@0.0.1-evm.55'
  - '@mainsail/serializer@0.0.1-evm.55'
  - '@mainsail/snapshot-legacy-exporter@0.0.1-evm.55'
  - '@mainsail/snapshot-legacy-importer@0.0.1-evm.55'
  - '@mainsail/state@0.0.1-evm.55'
  - '@mainsail/transaction-pool-broadcaster@0.0.1-evm.55'
  - '@mainsail/transaction-pool-service@0.0.1-evm.55'
  - '@mainsail/transaction-pool-worker@0.0.1-evm.55'
  - '@mainsail/utils@0.0.1-evm.55'
  - '@mainsail/validation@0.0.1-evm.55'
  - '@mainsail/validator@0.0.1-evm.55'
  - '@mainsail/webhooks@0.0.1-evm.55'
